### PR TITLE
Added style to show submenu

### PR DESCRIPTION
**Pull request by nestordedios**
Fixes issue #2.

### CODE REVIEW

**Comment by SahAssar** [comment]
@nestordedios You probably want to update the minified file and link to that instead, no?

**Comment by nestordedios** [comment]
@SahAssar Ops!! I have that too, I forgot to commit it. Give mi a minute I will commit and push.

**Comment by nestordedios** [comment]
Ok, Done!

**Comment by SahAssar** [comment]
@nestordedios Nice!

**Comment by Mikescops** [comment]
My bad, i'm so busy those days ^^ Thanks a lot !

**Comment by SahAssar** [comment]
Thanks for merging @Mikescops, could you perhaps also tag a minor release for it? :) Just to ease my mind regarding https://discuss.bolt.cm/d/25-theme-compatability-with-2-2-2-3-continuation-of-3731

**Comment by nestordedios** [comment]
You are Welcome @Mikescops !! I already thought you might have been busy with something else, hehe.

**Pull request merged**
